name: Releasepypi

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (A.B.C)
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment
        run: |
          echo 'VERSION="${{ inputs.version}}"' > ./githubstar/version.py
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Build
        run: |
          python -m pip install --upgrade pip build twine
          python -m build

      - name: Upload To Pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*  
        
